import { test } from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import { migrate } from '../src/db.js';

test('migração preserva produtos e movimentos existentes no Estoque geral', {skip: !process.env.DATABASE_URL}, async () => {
  const schema = `migration_${Date.now()}`;
  const admin = new pg.Pool({connectionString:process.env.DATABASE_URL});
  await admin.query(`CREATE SCHEMA ${schema}`);
  const db = new pg.Pool({connectionString:process.env.DATABASE_URL,options:`-c search_path=${schema}`});
  try {
    await db.query(`CREATE TABLE products (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(180) NOT NULL, unit varchar(30) NOT NULL, minimum integer NOT NULL DEFAULT 0, created_at timestamptz DEFAULT now());
      CREATE UNIQUE INDEX products_name_unique ON products(lower(trim(name)));
      CREATE TABLE movements (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id integer NOT NULL REFERENCES products(id), type varchar(7), quantity integer, occurred_at timestamptz DEFAULT now());
      INSERT INTO products(name,unit,minimum) VALUES ('Arroz','KG',1);
      INSERT INTO movements(product_id,type,quantity) VALUES (1,'ENTRADA',10),(1,'SAIDA',3);`);
    const before = (await db.query('SELECT * FROM movements ORDER BY id')).rows;
    await migrate(db);
    await migrate(db);
    const p = (await db.query('SELECT * FROM products')).rows[0];
    assert.equal(p.name,'Arroz'); assert.equal(p.warehouse_id,1);
    assert.deepEqual((await db.query('SELECT * FROM movements ORDER BY id')).rows,before);
    assert.deepEqual((await db.query('SELECT id,name FROM warehouses')).rows,[{id:1,name:'Estoque geral'}]);
  } finally {
    await db.end(); await admin.query(`DROP SCHEMA ${schema} CASCADE`); await admin.end();
  }
});
