BEGIN;
CREATE TABLE IF NOT EXISTS warehouses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL CHECK (length(trim(name)) > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS warehouses_name_unique ON warehouses (lower(trim(name)));
INSERT INTO warehouses(id, name) VALUES (1, 'Estoque geral') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('warehouses','id'), GREATEST((SELECT max(id) FROM warehouses), (SELECT last_value FROM warehouses_id_seq)), true);
CREATE TABLE IF NOT EXISTS products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(180) NOT NULL CHECK (length(trim(name)) > 0),
  unit varchar(30) NOT NULL CHECK (length(trim(unit)) > 0),
  minimum integer NOT NULL DEFAULT 0 CHECK (minimum >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);
-- Existing products retain their IDs and movement history in the initial warehouse.
ALTER TABLE products ADD COLUMN IF NOT EXISTS warehouse_id integer NOT NULL DEFAULT 1 REFERENCES warehouses(id);
DROP INDEX IF EXISTS products_name_unique;
CREATE UNIQUE INDEX IF NOT EXISTS products_warehouse_name_unique ON products (warehouse_id, lower(trim(name)));
CREATE TABLE IF NOT EXISTS movements (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id),
  type varchar(7) NOT NULL CHECK (type IN ('ENTRADA', 'SAIDA')),
  quantity integer NOT NULL CHECK (quantity > 0),
  occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS movements_product_date ON movements(product_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS movements_date ON movements(occurred_at DESC);
COMMIT;
